name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Tests
    uses: theforeman/actions/.github/workflows/test-gem.yml@v0
    with:
      command: bundle exec rake test
